name: gemo
description: A college-exclusive video chat app for students to connect, study, and socialize securely.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_functions: ^5.4.0
  google_fonts: ^6.2.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.4
  fluttertoast: ^8.2.12
  videosdk: ^1.3.1
  logging: ^1.3.0
  http: ^1.3.0
  collection: ^1.19.0
  flutter_riverpod: ^2.0.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  logger: ^2.5.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/gemo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
   - assets/background.png
   - assets/gemo.png
   - assets/HomeScreen.png
   - assets/images/default.png
   - assets/images/gold.png
   - assets/images/silver.png
   - assets/images/bronze.png
   - assets/images/music.png
   - assets/images/gaming.png
   - assets/images/movies.png
   - assets/images/sports.png
   - assets/images/travel.png
   - assets/images/fitness.png
   - assets/images/fashion.png
   - assets/images/food.png
   - assets/images/photography.png
   - assets/images/health.png
   - assets/images/business.png
   - assets/images/finance.png
   - assets/images/electricalengineering.png
   - assets/images/calculus.png
   - assets/images/physics.png
   - assets/images/chemistry.png
   - assets/images/economics.png
   - assets/images/psychology.png
   - assets/images/history.png
   - assets/images/computerscience.png
   - assets/images/mechanicalengineering.png
   - assets/images/civilengineering.png
   - assets/images/chemicalengineering.png
   - assets/images/bioengineering.png