// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA36cIcbyvtVVBRjaro80rT557YVpvrRHk',
    appId: '1:432626017857:web:babf3decead0926a7ec8c0',
    messagingSenderId: '432626017857',
    projectId: 'gemo-6f36e',
    authDomain: 'gemo-6f36e.firebaseapp.com',
    storageBucket: 'gemo-6f36e.firebasestorage.app',
    measurementId: 'G-TN0MMRN2W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8uR9VkVwv-lRBf9IRSQkt7LQrNyGgmj0',
    appId: '1:432626017857:android:e9b68d8f292475ed7ec8c0',
    messagingSenderId: '432626017857',
    projectId: 'gemo-6f36e',
    storageBucket: 'gemo-6f36e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA73qcrUoS-IEnKnYIJukjSbNzDuNOzSFo',
    appId: '1:432626017857:ios:f2fac88ef43b717b7ec8c0',
    messagingSenderId: '432626017857',
    projectId: 'gemo-6f36e',
    storageBucket: 'gemo-6f36e.firebasestorage.app',
    iosBundleId: 'com.example.gemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA73qcrUoS-IEnKnYIJukjSbNzDuNOzSFo',
    appId: '1:432626017857:ios:f2fac88ef43b717b7ec8c0',
    messagingSenderId: '432626017857',
    projectId: 'gemo-6f36e',
    storageBucket: 'gemo-6f36e.firebasestorage.app',
    iosBundleId: 'com.example.gemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA36cIcbyvtVVBRjaro80rT557YVpvrRHk',
    appId: '1:432626017857:web:089074f3ca952d627ec8c0',
    messagingSenderId: '432626017857',
    projectId: 'gemo-6f36e',
    authDomain: 'gemo-6f36e.firebaseapp.com',
    storageBucket: 'gemo-6f36e.firebasestorage.app',
    measurementId: 'G-NTYCJSPDGL',
  );
}
