const List<String> majorsList = [
  'Computer Science',
  'Biology',
  'Business',
  'Chemistry',
  'Communications',
  'Economics',
  'Education',
  'Engineering',
  'English',
  'Environmental Science',
  'Finance',
  'Graphic Design',
  'History',
  'Mathematics',
  'Marketing',
  'Nursing',
  'Physics',
  'Political Science',
  'Psychology',
  'Sociology',
  'Theater',
  'Undeclared',
];
